AllCops:
  Exclude:
    - Gemfile
    - quickstart.rb

require:
  - rubocop-rspec
  - rubocop
  - rubocop-performance

RSpec/HookArgument:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/InstanceVariable:
 Enabled: false

RSpec/LeakyConstantDeclaration:
  Enabled: false

RSpec/FilePath:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/MultipleExpectations:
  Enabled: false

Style/MixinUsage:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  Enabled: false

Naming/ConstantName:
  Enabled: false

Style/ColonMethodCall:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

Metrics/LineLength:
  Max: 150

Metrics/ClassLength:
  Max: 200
